[project]
name = "emotinews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.1",
    "diskcache>=5.6.3",
    "fastapi>=0.121.3",
    "httpx>=0.28.1",
    "newsapi-python>=0.2.7",
    "python-dotenv[cli]>=1.2.1",
    "pytz>=2025.2",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "fastapi[standard]>=0.121.3",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --tb=short"
